services:
    phpbbde.externalimgaslink.helper:
        class: phpbbde\externalimgaslink\helper
        arguments:
            - '@user'

    phpbbde.externalimgaslink.listener:
        class: phpbbde\externalimgaslink\event\listener
        arguments:
            - '@config'
            - '@service_container'
            - '@phpbbde.externalimgaslink.helper'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
